---
title: "Multiple Pages"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    navbar :
      - { title: "About", href: "https://example.com/about", align: right }
      - { icon: "fa-pencil", href: "https://www.naver.com", align: right}
---

Page 1
=============================================

This is an example. As you can see, flexdashboard can have text annotations.

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(knitr)
```

Column1
-----------------------------------------------------------------------
### Gauge ex1. Contact Rate

```{r}
gauge(35, min = 0, max = 100, symbol = '%',
      sectors = gaugeSectors(success = c(80, 100),
                             warning = c(40, 79),
                             danger = c(0, 39)
))

```

### Gauge ex2. Average Rating 

```{r}
rating = 42
gauge(rating, 0, 50, label = 'Test', gaugeSectors(
  success = c(41, 50), warning = c(21, 40), danger = c(0, 20)
))

```

### Text Annotation

One of the dashboard section can be used as a text area.
Markdown Grammers can be helpful here.
It is not that difficult.
Just have a try. 

Column2
-----------------------------------------------------------------------

Page 2 {data-orientation=rows}
=====================================================================

### ggplot2 chart 1

```{r}
ggplot(data=mtcars, aes(x=hp, y=mpg, color=as.factor(cyl))) +
  geom_point() +
  theme(legend.position="blank")

```


